name: Scrape Pok√©mon GO Data (Daily)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pogo-scraper-lock
  cancel-in-progress: false

jobs:
  scrape:
    uses: ./.github/workflows/scrape_reusable.yml
    with:
      freq: daily