name: Scrape Pok√©mon GO Data (Daily)

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pogo-daily
  cancel-in-progress: false

jobs:
  call-reusable:
    uses: ./.github/workflows/scrape_reusable.yml
    secrets: inherit
    with:
      freq: daily
