name: Scrape Pok√©mon GO Data (Monthly)

on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: pogo-monthly
  cancel-in-progress: false

jobs:
  call-reusable:
    uses: ./.github/workflows/scrape_reusable.yml
    secrets: inherit
    with:
      freq: monthly
